// components/border-generator.tsx
'use client'

import { useState, useRef } from 'react'
import { Button } from '@/components/ui/button'
import BorderGridPreview from './border-grid-preview'

interface BorderSettings {
  borderWidth: number
  gridCountX: number
  gridCountY: number
  gridSize: number
}

export default function BorderGenerator() {
  const [uploadedImage, setUploadedImage] = useState<string | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const [settings, setSettings] = useState<BorderSettings>({
    borderWidth: 40,
    gridCountX: 8,
    gridCountY: 5,
    gridSize: 60,
  })

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }

  const handleDragLeave = () => {
    setIsDragging(false)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer.files?.[0]
    if (file) {
      handleImageUpload(file)
    }
  }

  const handleImageUpload = (file: File) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      setUploadedImage(e.target?.result as string)
    }
    reader.readAsDataURL(file)
  }

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      handleImageUpload(file)
    }
  }

  const updateSetting = (key: keyof BorderSettings, value: number) => {
    setSettings((prev) => ({
      ...prev,
      [key]: value,
    }))
  }

  return (
    <div className="flex flex-col flex-1">
      <div className="h-80 bg-gradient-to-b from-emerald-300 to-emerald-200 border-b-4 border-orange-500 p-6 overflow-auto">
        <div className="max-w-7xl mx-auto">
          {!uploadedImage ? (
            // Upload Area
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              className={`border-2 border-dashed rounded-lg p-6 text-center cursor-pointer transition-all h-full flex items-center justify-center ${
                isDragging
                  ? 'border-orange-600 bg-orange-100'
                  : 'border-orange-400 bg-emerald-100'
              }`}
              onClick={() => fileInputRef.current?.click()}
            >
              <div>
                <p className="text-sm font-semibold text-slate-800">
                  拖放圖片到此或點擊上傳
                </p>
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleFileInputChange}
                className="hidden"
              />
            </div>
          ) : (
            // Settings Panel
            <div className="space-y-4">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {/* Border Width */}
                <div>
                  <label className="block text-xs font-bold text-slate-800 mb-1">
                    邊框寬度: {settings.borderWidth}px
                  </label>
                  <input
                    type="range"
                    min="10"
                    max="80"
                    step="5"
                    value={settings.borderWidth}
                    onChange={(e) => updateSetting('borderWidth', Number(e.target.value))}
                    className="w-full h-1.5 bg-slate-300 rounded-lg appearance-none cursor-pointer accent-orange-600"
                  />
                </div>

                {/* Grid Count X */}
                <div>
                  <label className="block text-xs font-bold text-slate-800 mb-1">
                    寬度網格數: {settings.gridCountX}
                  </label>
                  <input
                    type="range"
                    min="3"
                    max="12"
                    step="1"
                    value={settings.gridCountX}
                    onChange={(e) => updateSetting('gridCountX', Number(e.target.value))}
                    className="w-full h-1.5 bg-slate-300 rounded-lg appearance-none cursor-pointer accent-orange-600"
                  />
                </div>

                {/* Grid Count Y */}
                <div>
                  <label className="block text-xs font-bold text-slate-800 mb-1">
                    高度網格數: {settings.gridCountY}
                  </label>
                  <input
                    type="range"
                    min="2"
                    max="8"
                    step="1"
                    value={settings.gridCountY}
                    onChange={(e) => updateSetting('gridCountY', Number(e.target.value))}
                    className="w-full h-1.5 bg-slate-300 rounded-lg appearance-none cursor-pointer accent-orange-600"
                  />
                </div>

                {/* Grid Size */}
                <div>
                  <label className="block text-xs font-bold text-slate-800 mb-1">
                    網格大小: {settings.gridSize}px
                  </label>
                  <input
                    type="range"
                    min="30"
                    max="100"
                    step="5"
                    value={settings.gridSize}
                    onChange={(e) => updateSetting('gridSize', Number(e.target.value))}
                    className="w-full h-1.5 bg-slate-300 rounded-lg appearance-none cursor-pointer accent-orange-600"
                  />
                </div>
              </div>

              {/* Reset Button */}
              <div className="flex gap-2 justify-start">
                <Button
                  onClick={() => setUploadedImage(null)}
                  className="bg-orange-600 hover:bg-orange-700 text-white text-xs px-3 py-1"
                >
                  重新上傳
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Content Area - Left Image + Right Grid */}
      {uploadedImage && (
        <div className="flex-1 flex overflow-hidden">
          <div className="w-1/2 bg-blue-300 border-r-4 border-orange-500 flex items-center justify-center p-4 overflow-auto">
            <img
              src={uploadedImage || "/placeholder.svg"}
              alt="Uploaded"
              className="max-w-full max-h-full object-contain"
            />
          </div>

          <div className="w-1/2 bg-pink-200 border-r-4 border-orange-500 flex items-center justify-center p-4 overflow-auto">
            <BorderGridPreview uploadedImage={uploadedImage} settings={settings} />
          </div>
        </div>
      )}
    </div>
  )
}

// src/app/components/border-generator/border-generator.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef } from '@angular/core';
import { BorderService, BorderSettings } from '../../services/border.service';

@Component({
  selector: 'app-border-generator',
  templateUrl: './border-generator.component.html',
  styleUrls: ['./border-generator.component.scss']
})
export class BorderGeneratorComponent implements OnInit, OnDestroy {
  @ViewChild('fileInput', { static: false }) fileInput!: ElementRef<HTMLInputElement>;

  uploadedImage: string | null = null;
  isDragging = false;
  settings: BorderSettings = {
    borderWidth: 40,
    gridCountX: 8,
    gridCountY: 5,
    gridSize: 60
  };

  constructor(private borderService: BorderService) {}

  private subscriptions: any[] = [];

  ngOnInit(): void {
    // 訂閱圖片上傳狀態
    const imageSub = this.borderService.uploadedImage$.subscribe(image => {
      this.uploadedImage = image;
    });
    this.subscriptions.push(imageSub);

    // 訂閱設置變更
    const settingsSub = this.borderService.settings$.subscribe(settings => {
      this.settings = settings;
    });
    this.subscriptions.push(settingsSub);
  }

  ngOnDestroy(): void {
    // 清理訂閱
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    this.isDragging = true;
  }

  onDragLeave(): void {
    this.isDragging = false;
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.isDragging = false;
    const file = event.dataTransfer?.files?.[0];
    if (file) {
      this.handleImageUpload(file);
    }
  }

  onFileInputChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      this.handleImageUpload(file);
    }
  }

  handleImageUpload(file: File): void {
    // 驗證文件類型
    if (!file.type.startsWith('image/')) {
      console.error('請選擇圖片文件');
      return;
    }

    // 限制文件大小（例如 10MB）
    const maxSize = 10 * 1024 * 1024; // 10MB
    if (file.size > maxSize) {
      console.error('圖片文件太大，請選擇小於 10MB 的圖片');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string;
      this.borderService.setUploadedImage(result);
    };
    reader.onerror = () => {
      console.error('讀取圖片文件時發生錯誤');
    };
    reader.readAsDataURL(file);
  }

  openFileInput(): void {
    this.fileInput.nativeElement.click();
  }

  resetUpload(): void {
    this.borderService.setUploadedImage(null);
  }

  updateSetting(key: keyof BorderSettings, value: number): void {
    this.borderService.updateSettings({ [key]: value });
  }
}


<div class="border-generator-container">
  <!-- Upload/Settings Panel -->
  <div class="settings-panel">
    <div class="panel-content">
      <ng-container *ngIf="!uploadedImage; else settingsTemplate">
        <!-- Upload Area -->
        <div
          class="upload-area"
          [class.dragging]="isDragging"
          (dragover)="onDragOver($event)"
          (dragleave)="onDragLeave()"
          (drop)="onDrop($event)"
          (click)="openFileInput()">
          <p class="upload-text">拖放圖片到此或點擊上傳</p>
          <input
            #fileInput
            type="file"
            accept="image/*"
            (change)="onFileInputChange($event)"
            class="hidden-input" />
        </div>
      </ng-container>

      <ng-template #settingsTemplate>
        <!-- Settings Panel -->
        <div class="settings-content">
          <div class="settings-grid">
            <!-- Border Width -->
            <div class="setting-item">
              <label class="setting-label">
                邊框寬度: {{ settings.borderWidth }}px
              </label>
              <input
                type="range"
                min="10"
                max="80"
                step="5"
                [value]="settings.borderWidth"
                (input)="updateSetting('borderWidth', +$any($event.target).value)"
                class="range-input" />
            </div>

            <!-- Grid Count X -->
            <div class="setting-item">
              <label class="setting-label">
                寬度網格數: {{ settings.gridCountX }}
              </label>
              <input
                type="range"
                min="3"
                max="12"
                step="1"
                [value]="settings.gridCountX"
                (input)="updateSetting('gridCountX', +$any($event.target).value)"
                class="range-input" />
            </div>

            <!-- Grid Count Y -->
            <div class="setting-item">
              <label class="setting-label">
                高度網格數: {{ settings.gridCountY }}
              </label>
              <input
                type="range"
                min="2"
                max="8"
                step="1"
                [value]="settings.gridCountY"
                (input)="updateSetting('gridCountY', +$any($event.target).value)"
                class="range-input" />
            </div>

            <!-- Grid Size -->
            <div class="setting-item">
              <label class="setting-label">
                網格大小: {{ settings.gridSize }}px
              </label>
              <input
                type="range"
                min="30"
                max="100"
                step="5"
                [value]="settings.gridSize"
                (input)="updateSetting('gridSize', +$any($event.target).value)"
                class="range-input" />
            </div>
          </div>

          <!-- Reset Button -->
          <div class="button-group">
            <ion-button
              color="warning"
              size="small"
              (click)="resetUpload()">
              重新上傳
            </ion-button>
          </div>
        </div>
      </ng-template>
    </div>
  </div>

  <!-- Content Area - Left Image + Right Grid -->
  <div class="content-area" *ngIf="uploadedImage">
    <div class="image-panel">
      <img
        [src]="uploadedImage"
        alt="Uploaded"
        class="preview-image" />
    </div>

    <div class="grid-panel">
      <app-border-grid-preview
        [uploadedImage]="uploadedImage"
        [settings]="settings">
      </app-border-grid-preview>
    </div>
  </div>
</div>
