// src/app/components/border-grid-preview/border-grid-preview.component.ts
import { Component, Input } from '@angular/core';
import { BorderSettings } from '../../services/border.service';

@Component({
  selector: 'app-border-grid-preview',
  templateUrl: './border-grid-preview.component.html',
  styleUrls: ['./border-grid-preview.component.scss']
})
export class BorderGridPreviewComponent {
  @Input() uploadedImage!: string;
  @Input() settings!: BorderSettings;

  get gridCells(): number[] {
    const total = this.settings.gridCountX * this.settings.gridCountY;
    return Array.from({ length: total }, (_, i) => i);
  }

  isBorderCell(index: number): boolean {
    const row = Math.floor(index / this.settings.gridCountX);
    const col = index % this.settings.gridCountX;
    return (
      row === 0 ||
      row === this.settings.gridCountY - 1 ||
      col === 0 ||
      col === this.settings.gridCountX - 1
    );
  }

  getGridStyle(): { [key: string]: string } {
    return {
      display: 'grid',
      gridTemplateColumns: `repeat(${this.settings.gridCountX}, ${this.settings.gridSize}px)`,
      gap: '2px',
      padding: '2px'
    };
  }

  getCellStyle(index: number): { [key: string]: string } {
    const isBorder = this.isBorderCell(index);
    return {
      width: `${this.settings.gridSize}px`,
      height: `${this.settings.gridSize}px`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundImage: !isBorder ? `url(${this.uploadedImage})` : 'none',
      backgroundSize: 'cover',
      backgroundPosition: 'center'
    };
  }
}


<div class="grid-container" [ngStyle]="getGridStyle()">
  <div
    *ngFor="let cell of gridCells; let i = index"
    class="grid-cell"
    [class.border-cell]="isBorderCell(i)"
    [class.center-cell]="!isBorderCell(i)"
    [ngStyle]="getCellStyle(i)">
  </div>
</div>

// components/border-grid-preview.tsx
'use client'

interface BorderSettings {
  borderWidth: number
  gridCountX: number
  gridCountY: number
  gridSize: number
}

interface BorderGridPreviewProps {
  uploadedImage: string
  settings: BorderSettings
}

export default function BorderGridPreview({
  uploadedImage,
  settings,
}: BorderGridPreviewProps) {
  const { borderWidth, gridCountX, gridCountY, gridSize } = settings

  // Calculate center area dimensions
  const centerWidth = gridSize * (gridCountX - 2)
  const centerHeight = gridSize * (gridCountY - 2)

  return (
    <div
      className="relative bg-white"
      style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${gridCountX}, ${gridSize}px)`,
        gap: '2px',
        padding: '2px',
      }}
    >
      {Array.from({ length: gridCountX * gridCountY }).map((_, index) => {
        const row = Math.floor(index / gridCountX)
        const col = index % gridCountX

        // Check if this grid cell is part of the border or center
        const isBorder =
          row === 0 ||
          row === gridCountY - 1 ||
          col === 0 ||
          col === gridCountX - 1

        return (
          <div
            key={index}
            className={`border-2 ${
              isBorder
                ? 'bg-pink-300 border-orange-600'
                : 'bg-blue-300 border-yellow-400'
            }`}
            style={{
              width: `${gridSize}px`,
              height: `${gridSize}px`,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              // Center area shows the image
              backgroundImage: !isBorder
                ? `url(${uploadedImage})`
                : undefined,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
            }}
          />
        )
      })}
    </div>
  )
}
